<a href="https://colab.research.google.com/github/tvaditya/intro_ds_and_ml/blob/main/%5BNLP6%5DWordEmebddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


In [3]:
word_to_idx = {"I": 0, "love": 1, "eating":2, "and":3, "sleeping":4}
embeddings = nn.Embedding(5, 7)    # 5 words in vocab, embedding size is 7
word_index = torch.tensor([word_to_idx["love"]])
print(word_index)


tensor([1])


In [4]:
love = embeddings(word_index)
print(love)
print(love.shape)

tensor([[ 0.3543, -1.8150, -0.3814, -0.5924, -2.0484,  0.2436,  0.0745]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([1, 7])


In [5]:
all_ind = torch.tensor([w for w in range(5)], dtype = torch.long)
all_words = embeddings(all_ind)
print(all_ind)
print(all_words)
print(all_words.shape)



tensor([0, 1, 2, 3, 4])
tensor([[-1.2729,  0.2622,  0.3793,  1.6928, -0.4182, -0.6380, -0.1551],
        [ 0.3543, -1.8150, -0.3814, -0.5924, -2.0484,  0.2436,  0.0745],
        [-0.8729,  0.1625, -0.4501,  0.9907,  0.5966,  0.4121,  1.2168],
        [ 0.6266,  0.7605, -0.0757,  0.4142,  1.6269, -0.3233, -1.2775],
        [ 0.9509, -0.7878,  0.0454, -0.1881,  1.0582, -1.2233,  1.0552]],
       grad_fn=<EmbeddingBackward0>)
torch.Size([5, 7])


In [ ]:
# Tem as funções de similaridade nessa lib e em outras que voces podem usar para ver.