<a href="https://colab.research.google.com/github/tvaditya/intro_ds_and_ml/blob/main/%5BNLP7%5DSentimentalWithTransformers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.tokenize import RegexpTokenizer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [2]:
import matplotlib.pyplot as plt 
import seaborn as sns

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/stacktecnologias/stack-repo/master/Tweets_Mg.csv')
df.head()

Unnamed: 0                      Created At  \
0           0  Sun Jan 08 01:22:05 +0000 2017   
1           1  Sun Jan 08 01:49:01 +0000 2017   
2           2  Sun Jan 08 01:01:46 +0000 2017   
3           3  Wed Jan 04 21:43:51 +0000 2017   
4           4  Mon Jan 09 15:08:21 +0000 2017   

                                                Text  \
0  ���⛪ @ Catedral de Santo Antônio - Governador ...   
1  � @ Governador Valadares, Minas Gerais https:/...   
2  �� @ Governador Valadares, Minas Gerais https:...   
3                        ��� https://t.co/BnDsO34qK0   
4  ��� PSOL vai questionar aumento de vereadores ...   

   Geo Coordinates.latitude  Geo Coordinates.longitude User Location  \
0                       NaN                        NaN        Brasil   
1                  -41.9333                     -18.85           NaN   
2                  -41.9333                     -18.85           NaN   
3                       NaN                        NaN           NaN   
4                       NaN                        NaN           NaN   

               Username User Screen Name  Retweet Count Classificacao  ...  \
0  Leonardo C Schneider    LeoCSchneider              0        Neutro  ...   
1               Wândell         klefnews              0        Neutro  ...   
2               Wândell         klefnews              0        Neutro  ...   
3         Ana estudando  estudandoconcur              0        Neutro  ...   
4                 Emily         Milly777              0      Negativo  ...   

  Unnamed: 15  Unnamed: 16  Unnamed: 17  Unnamed: 18  Unnamed: 19  \
0         NaN          NaN          NaN          NaN          NaN   
1         NaN          NaN          NaN          NaN          NaN   
2         NaN          NaN          NaN          NaN          NaN   
3         NaN          NaN          NaN          NaN          NaN   
4         NaN          NaN          NaN          NaN          NaN   

   Unnamed: 20  Unnamed: 21  Unnamed: 22  Unnamed: 23  Unnamed: 24  
0          NaN          NaN          NaN          NaN          NaN  
1          NaN          NaN          NaN          NaN          NaN  
2          NaN          NaN          NaN          NaN          NaN  
3          NaN          NaN          NaN          NaN          NaN  
4          NaN          NaN          NaN          NaN          NaN  

[5 rows x 26 columns]

In [4]:
df.columns

Index(['Unnamed: 0', 'Created At', 'Text', 'Geo Coordinates.latitude',
       'Geo Coordinates.longitude', 'User Location', 'Username',
       'User Screen Name', 'Retweet Count', 'Classificacao', 'Observação',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24'],
      dtype='object')

In [5]:
print(df['Classificacao'][0])
df['Text'][0]

Neutro


'���⛪ @ Catedral de Santo Antônio - Governador Valadares/MG https://t.co/JSbKamIqUJ'

In [6]:
def hashtag(text):
  hash = re.findall(r"#(\w+)", text)
  return hash

hashtag(" #blalbla")

['blalbla']

In [7]:
def remove_username(text):
  clean_text = re.sub('(@[A-Za-z]+[A-Za-z0-9-_]+)', '', text)
  return clean_text

In [8]:
def remove_links_http(text):
  text = re.sub(r'http\S+','', text)
  # text = re.sub(r'https','', text)
  text = re.sub(r'bit.ly/\S+','', text)
  text = text.strip('[link]')

  return text

In [9]:
def remove_html_tag(text):
  clean_text = re.compile('<.*?>')
  return clean_text.sub(r'', text)

In [10]:
# Será que remove caracteres estranhos???
def non_ascii(s):
  return "".join(i for i in s if ord(i)<128)

def lower(text):
  return text.lower()

In [ ]:
# def remove_stopwords(text):
#   stopptbr = set(stopwords.words("portuguese"))
#   clean_text = ' '.join([word for word in text.split() if word not in stopptbr])

#   return clean_text

In [11]:
def remove_email_address(text):
  email = re.compile(r'[\w\.-]+@[\w\.-]+')
  return email.sub(r'',text)

In [ ]:
# def remove_punct(text):
#   token=RegexpTokenizer(r'\w+')#regex
#   text = token.tokenize(text)
#   text= " ".join(text)
#   return text



In [12]:
# df['hashtag'] = df.Text.apply(func=hashtag)
df['CleanText'] = df.Text.apply(func=remove_links_http)
df['CleanText'] = df.CleanText.apply(func=remove_username)

df['CleanText'] = df.CleanText.apply(func=remove_html_tag)
df['CleanText'] = df.CleanText.apply(func=non_ascii)
df['CleanText'] = df.CleanText.apply(func=lower)
# df['CleanText'] = df.CleanText.apply(func=remove_stopwords)
df['CleanText'] = df.CleanText.apply(func=remove_email_address)
# df['CleanText'] = df.CleanText.apply(func=remove_punct)

In [13]:
# df_new = df[['Text', 'Classificacao', 'hashtag', 'CleanText']]
df_new = df[['Text', 'Classificacao', 'CleanText']]

df_new.head()

Text Classificacao  \
0  ���⛪ @ Catedral de Santo Antônio - Governador ...        Neutro   
1  � @ Governador Valadares, Minas Gerais https:/...        Neutro   
2  �� @ Governador Valadares, Minas Gerais https:...        Neutro   
3                        ��� https://t.co/BnDsO34qK0        Neutro   
4  ��� PSOL vai questionar aumento de vereadores ...      Negativo   

                                           CleanText  
0   @ catedral de santo antnio - governador valad...  
1              @ governador valadares, minas gerais   
2              @ governador valadares, minas gerais   
3                                                     
4   psol vai questionar aumento de vereadores e p...

In [14]:
dicio = {'Neutro': 0, 'Negativo': 1, 'Positivo': 2}
df_new = df_new.replace({"Classificacao": dicio})

In [15]:
df_new.head()

Text  Classificacao  \
0  ���⛪ @ Catedral de Santo Antônio - Governador ...              0   
1  � @ Governador Valadares, Minas Gerais https:/...              0   
2  �� @ Governador Valadares, Minas Gerais https:...              0   
3                        ��� https://t.co/BnDsO34qK0              0   
4  ��� PSOL vai questionar aumento de vereadores ...              1   

                                           CleanText  
0   @ catedral de santo antnio - governador valad...  
1              @ governador valadares, minas gerais   
2              @ governador valadares, minas gerais   
3                                                     
4   psol vai questionar aumento de vereadores e p...

In [16]:
df_new.Classificacao.value_counts()

2    3300
0    2453
1    2446
Name: Classificacao, dtype: int64

In [17]:
df_new[df_new['Classificacao'] == 2].head(10)

Text  Classificacao  \
65   #DefesaAgropecuária "Governo de Minas Gerais a...              2   
66   #EBC Governo de Minas investiga casos suspeito...              2   
87   #Minas vai dobrar oferta de trabalho e estudo ...              2   
88   #Minas vai dobrar oferta de trabalho e estudo ...              2   
108  #SUS Minas Gerais recebe recurso máximo dispon...              2   
163  @diegocabral75 @exame aí em MG, ta td bem? Pim...              2   
199  @israel_massa @ferrisss @JornalOGlobo pelo men...              2   
225  @madeleinelacsko Em MG e SP,o Estado tem razoá...              2   
226                      @Madonegatti MG melhor estado              2   
244  @MrSincero_ @klyfor @MBLivre @MBLivreBH Minas ...              2   

                                             CleanText  
65   #defesaagropecuria "governo de minas gerais ap...  
66   #ebc governo de minas investiga casos suspeito...  
87   #minas vai dobrar oferta de trabalho e estudo ...  
88   #minas vai dobrar oferta de trabalho e estudo ...  
108  #sus minas gerais recebe recurso mximo disponi...  
163    a em mg, ta td bem? pimentel cada dia fazend...  
199     pelo menos 1 coisa p se orgulhar do governo...  
225   em mg e sp,o estado tem razovel controle sobr...  
226                                   mg melhor estado  
244      minas foi governada de 2003 a 2014 pelo ps...

In [18]:
df_new[df_new['Classificacao'] == 1].head(10)

Text  Classificacao  \
4   ��� PSOL vai questionar aumento de vereadores ...              1   
8   "BB e governo de Minas travam disputa sobre de...              1   
12  "erro desconhecido" é mato! Aliás, é da secret...              1   
16  "Mesmo sem muito dinheiro no caixa o governo d...              1   
25  "uso de aeronave pertencente ao  Estado de MG,...              1   
29  #Alerta - Nome da CEEE é utilizado em golpe no...              1   
43  #beta #betalab #mg Governo em calamidade finan...              1   
72  #i5gornascimento @i5gornascimento g1 Prefeito ...              1   
93  #noticiasdorenan Em calamidade financeira, gov...              1   
95  #noticiasdorenan Uso de depósitos judiciais pe...              1   

                                            CleanText  
4    psol vai questionar aumento de vereadores e p...  
8   "bb e governo de minas travam disputa sobre de...  
12  "erro desconhecido"  mato! alis,  da secretari...  
16  "mesmo sem muito dinheiro no caixa o governo d...  
25  "uso de aeronave pertencente ao  estado de mg,...  
29  #alerta - nome da ceee  utilizado em golpe no ...  
43  #beta #betalab #mg governo em calamidade finan...  
72  #i5gornascimento  g1 prefeito de aimors decret...  
93  #noticiasdorenan em calamidade financeira, gov...  
95  #noticiasdorenan uso de depsitos judiciais pel...

In [19]:
df_new[df_new['Classificacao'] == 0].head(10)

Text  Classificacao  \
0   ���⛪ @ Catedral de Santo Antônio - Governador ...              0   
1   � @ Governador Valadares, Minas Gerais https:/...              0   
2   �� @ Governador Valadares, Minas Gerais https:...              0   
3                         ��� https://t.co/BnDsO34qK0              0   
5   " bom é bandido morto"\nDeputado Cabo Júlio é ...              0   
6   "..E 25% dos mineiros dizem não torcer para ti...              0   
7   "A gigantesca barba do mal" em destaque no cad...              0   
9   "com vcs bh fica pequena!" Belo Horizonte (pro...              0   
10  "Daí a gente visita governador valadares"\n"Qu...              0   
11  "É bonita e é bonita..." \n#latergram #ibituru...              0   

                                            CleanText  
0    @ catedral de santo antnio - governador valad...  
1               @ governador valadares, minas gerais   
2               @ governador valadares, minas gerais   
3                                                      
5   " bom  bandido morto"\ndeputado cabo jlio  con...  
6   "..e 25% dos mineiros dizem no torcer para tim...  
7   "a gigantesca barba do mal" em destaque no cad...  
9   "com vcs bh fica pequena!" belo horizonte (pro...  
10  "da a gente visita governador valadares"\n"que...  
11  " bonita e  bonita..." \n#latergram #ibituruna...

In [20]:
# Usando transformers
import numpy as np

# Podem reduzir pois dificilmente teremos neste conjunto algo maior que 50 palavras
seq_len = 512
num_samples = len(df)

num_samples, seq_len

(8199, 512)

In [21]:
!pip install transformers

     |████████████████████████████████| 3.8 MB 8.0 MB/s 
     |████████████████████████████████| 895 kB 56.6 MB/s 
     |████████████████████████████████| 596 kB 70.0 MB/s 
     |████████████████████████████████| 67 kB 7.1 MB/s 
     |████████████████████████████████| 6.5 MB 36.3 MB/s 
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


In [22]:
from transformers import BertTokenizer

# initialize tokenizer
tokenizer = BertTokenizer.from_pretrained('adalbertojunior/distilbert-portuguese-cased')

Downloading:   0%|          | 0.00/205k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/513 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/624 [00:00<?, ?B/s]

In [23]:
# tokenize - com numpy arrays
tokens = tokenizer(df['CleanText'].tolist(), max_length=seq_len, truncation=True,
                   padding='max_length', add_special_tokens=True,
                   return_tensors='np')

In [24]:
tokens.keys()

dict_keys(['input_ids', 'token_type_ids', 'attention_mask'])

In [25]:
tokens['input_ids'][:10]

array([[  101,   137, 12000, ...,     0,     0,     0],
       [  101,   137,  3261, ...,     0,     0,     0],
       [  101,   137,  3261, ...,     0,     0,     0],
       ...,
       [  101,   107,   123, ...,     0,     0,     0],
       [  101,   107,   235, ...,     0,     0,     0],
       [  101,   107,   170, ...,     0,     0,     0]])

In [26]:
tokens['token_type_ids'][:10]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [27]:
tokens['attention_mask'][:10]

array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]])

In [28]:
with open('tweetsbr-xids.npy', 'wb') as f:
    np.save(f, tokens['input_ids'])
with open('tweetsbr-xmask.npy', 'wb') as f:
    np.save(f, tokens['attention_mask'])

In [29]:
del tokens

In [30]:
arr = df_new['Classificacao'].values

In [31]:
type(arr[0])

numpy.int64

In [32]:
arr.max()

2

In [33]:
# we then initialize the zero array
labels = np.zeros((num_samples, arr.max()+1))
labels.shape

(8199, 3)

In [34]:
labels

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       ...,
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
labels[np.arange(num_samples), arr] = 1

labels

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [36]:
labels.shape

(8199, 3)

In [37]:
with open('tweetsbr-labels.npy', 'wb') as f:
    np.save(f, labels)

In [ ]:
# Input pipe-line

In [38]:
import numpy as np

with open('tweetsbr-xids.npy', 'rb') as f:
    Xids = np.load(f, allow_pickle=True)
with open('tweetsbr-xmask.npy', 'rb') as f:
    Xmask = np.load(f, allow_pickle=True)
with open('tweetsbr-labels.npy', 'rb') as f:
    labels = np.load(f, allow_pickle=True)

In [39]:
import tensorflow as tf

dataset = tf.data.Dataset.from_tensor_slices((Xids, Xmask, labels))

dataset.take(1)

<TakeDataset element_spec=(TensorSpec(shape=(512,), dtype=tf.int64, name=None), TensorSpec(shape=(512,), dtype=tf.int64, name=None), TensorSpec(shape=(3,), dtype=tf.float64, name=None))>

In [40]:
def map_func(input_ids, masks, labels):
    # we convert our three-item tuple into a two-item tuple where the input item is a dictionary
    return {'input_ids': input_ids, 'attention_mask': masks}, labels

# then we use the dataset map method to apply this transformation
dataset = dataset.map(map_func)

dataset.take(1)

<TakeDataset element_spec=({'input_ids': TensorSpec(shape=(512,), dtype=tf.int64, name=None), 'attention_mask': TensorSpec(shape=(512,), dtype=tf.int64, name=None)}, TensorSpec(shape=(3,), dtype=tf.float64, name=None))>

In [41]:
batch_size = 16

dataset = dataset.shuffle(10000).batch(batch_size, drop_remainder=True)

dataset.take(1)

<TakeDataset element_spec=({'input_ids': TensorSpec(shape=(16, 512), dtype=tf.int64, name=None), 'attention_mask': TensorSpec(shape=(16, 512), dtype=tf.int64, name=None)}, TensorSpec(shape=(16, 3), dtype=tf.float64, name=None))>

In [42]:
split = 0.7

# we need to calculate how many batches must be taken to create 70% training set
size = int((Xids.shape[0] / batch_size) * split)

size

358

In [43]:
train_ds = dataset.take(size)
val_ds = dataset.skip(size)

# free up memory
del dataset

In [44]:
len(train_ds)

358

In [45]:
len(val_ds)

154

In [46]:
tf.data.experimental.save(train_ds, 'train')
tf.data.experimental.save(val_ds, 'val')

In [47]:
train_ds.element_spec

({'attention_mask': TensorSpec(shape=(16, 512), dtype=tf.int64, name=None),
  'input_ids': TensorSpec(shape=(16, 512), dtype=tf.int64, name=None)},
 TensorSpec(shape=(16, 3), dtype=tf.float64, name=None))

In [48]:
val_ds.element_spec == train_ds.element_spec

True

In [49]:
ds = tf.data.experimental.load('train', element_spec=train_ds.element_spec)

In [50]:
from transformers import TFAutoModelForSequenceClassification

bert = TFAutoModelForSequenceClassification.from_pretrained('adalbertojunior/distilbert-portuguese-cased', from_pt=True)

# we can view the model using the summary method
bert.summary()

Downloading:   0%|          | 0.00/253M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertForSequenceClassification: ['embeddings.position_ids']
- This IS expected if you are initializing TFBertForSequenceClassification from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertForSequenceClassification from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
Some weights or buffers of the TF 2.0 model TFBertForSequenceClassification were not initialized from the PyTorch model and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


Model: "tf_bert_for_sequence_classification"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 bert (TFBertMainLayer)      multiple                  66395904  
                                                                 
 dropout_19 (Dropout)        multiple                  0         
                                                                 
 classifier (Dense)          multiple                  1538      
                                                                 
Total params: 66,397,442
Trainable params: 66,397,442
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# https://jalammar.github.io/illustrated-transformer/

In [51]:
# Criar o modelo e treinar
# duas camadas de entrada, um para "input ID" e outro "Mask"
input_ids = tf.keras.layers.Input(shape=(512,), name='input_ids', dtype='int32')
mask = tf.keras.layers.Input(shape=(512,), name='attention_mask', dtype='int32')

# we access the transformer model within our bert object using the bert attribute (eg bert.bert instead of bert)
# https://www.analyticsvidhya.com/blog/2021/09/an-explanatory-guide-to-bert-tokenizer/
embeddings = bert.bert(input_ids, attention_mask=mask)[1]  
# convert bert embeddings into 3 output classes
x = tf.keras.layers.Dense(1024, activation='relu')(embeddings)
y = tf.keras.layers.Dense(3, activation='softmax', name='outputs')(x)

In [52]:
# Inicializar o modelo
model = tf.keras.Model(inputs=[input_ids, mask], outputs=y)

model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_ids (InputLayer)         [(None, 512)]        0           []                               
                                                                                                  
 attention_mask (InputLayer)    [(None, 512)]        0           []                               
                                                                                                  
 bert (TFBertMainLayer)         TFBaseModelOutputWi  66395904    ['input_ids[0][0]',              
                                thPoolingAndCrossAt               'attention_mask[0][0]']         
                                tentions(last_hidde                                               
                                n_state=(None, 512,                                           

In [53]:
optimizer = tf.keras.optimizers.Adam(lr=1e-5, decay=1e-6)
loss = tf.keras.losses.CategoricalCrossentropy()
acc = tf.keras.metrics.CategoricalAccuracy('accuracy')

model.compile(optimizer=optimizer, loss=loss, metrics=[acc])



/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/adam.py:105: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


{'attention_mask': TensorSpec(shape=(16, 512), dtype=tf.int64, name=None),
  'input_ids': TensorSpec(shape=(16, 512), dtype=tf.int64, name=None)},
 TensorSpec(shape=(16, 3), dtype=tf.float64, name=None)

In [54]:
element_spec = ({'input_ids': tf.TensorSpec(shape=(16, 512), dtype=tf.int64, name=None),
                 'attention_mask': tf.TensorSpec(shape=(16, 512), dtype=tf.int64, name=None)},
                tf.TensorSpec(shape=(16, 3), dtype=tf.float64, name=None))

# load the training and validation sets
train_ds = tf.data.experimental.load('train', element_spec=element_spec)
val_ds = tf.data.experimental.load('val', element_spec=element_spec)

# view the input format
train_ds.take(1)



<TakeDataset element_spec=({'input_ids': TensorSpec(shape=(16, 512), dtype=tf.int64, name=None), 'attention_mask': TensorSpec(shape=(16, 512), dtype=tf.int64, name=None)}, TensorSpec(shape=(16, 3), dtype=tf.float64, name=None))>

In [56]:
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=2
)

Epoch 1/2
358/358 [==============================] - 367s 1s/step - loss: 0.2596 - accuracy: 0.9146 - val_loss: 0.1005 - val_accuracy: 0.9683
Epoch 2/2
358/358 [==============================] - 371s 1s/step - loss: 0.0870 - accuracy: 0.9736 - val_loss: 0.0753 - val_accuracy: 0.9801


In [57]:
model.save('analise_sentimento_ptbr')

INFO:tensorflow:Assets written to: analise_sentimento_ptbr/assets


INFO:tensorflow:Assets written to: analise_sentimento_ptbr/assets


In [58]:
#model = tf.keras.models.load_model('analise_sentimento_ptbr')

In [59]:
def prep_data(text):
    tokens = tokenizer.encode_plus(text, max_length=512,
                                   truncation=True, padding='max_length',
                                   add_special_tokens=True, return_token_type_ids=False,
                                   return_tensors='tf')
    # tokenizer retorna int32 por isso precisamos fazer um casting pra retirnar int64
    return {'input_ids': tf.cast(tokens['input_ids'], tf.int64),
            'attention_mask': tf.cast(tokens['attention_mask'], tf.int64)}

In [60]:
model.predict(prep_data("Olá mundo"))

array([[0.860271  , 0.0388419 , 0.10088713]], dtype=float32)

In [61]:
model.predict(prep_data("Camara aprova aumento de salarios"))[0]

array([0.07631878, 0.09223535, 0.8314459 ], dtype=float32)

In [62]:
model.predict(prep_data("Esse livro é horrível"))[0]

array([0.7199117 , 0.17969424, 0.10039416], dtype=float32)

In [63]:
frases = ["1 bilhão sumiu das contas do governo", "empresa aumenta", "Visite o parque da cidade"]

In [64]:
for frase in frases:
  probs = model.predict(prep_data(frase))[0]
  print(np.argmax(probs))

1
0
0


In [ ]:
# Como posso melhorar esse modelo?

In [ ]:
df_new['CleanText'].iloc[251]